/* eslint-disable react-hooks/rules-of-hooks */
export const staticUrls = [
  {
    title: 'Home',
    url: '/',
    lastModified: new Date(),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    title: 'About',
    url: '/about',
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.8,
  },
  {
    title: 'My skills',
    url: '/about/skills',
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 1,
  },
  {
    title: 'All projects',
    url: '/project',
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: 0.6,
  },
  {
    title: 'All posts',
    url: '/post',
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: 0.6,
  },
  {
    title: 'Portfolio',
    url: '/portfolio',
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.6,
  },
  {
    title: 'Portfolio graphics',
    url: '/portfolio/graphics',
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.6,
  },
  {
    title: 'Portfolio dev',
    url: '/portfolio/dev',
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.6,
  },
  {
    title: 'Showcase 2023',
    url: '/showcase/2023',
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: 1,
  },
  {
    title: 'Showcase 2022',
    url: '/showcase/2022',
    lastModified: new Date(),
    changeFrequency: 'never',
    priority: 0.8,
  },
  {
    title: 'GLSL Editor',
    url: '/tools/glslEditor',
    lastModified: new Date(),
    changeFrequency: 'monthly',
    priority: 0.4,
  },
  {
    title: 'Productivity clock',
    url: '/tools/clock',
    lastModified: new Date(),
    changeFrequency: 'monthly',
    priority: 0.4,
  },
]
